version: '3.8'
services:
  permissions-api:
    build: .
    container_name: permissions-api
    ports:
      - "5000:80"
    depends_on:
      - kafka
      - elasticsearch
    environment:
      KAFKA_BROKER: kafka:9092
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - permissions-net

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - permissions-net

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - permissions-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - permissions-net

networks:
  permissions-net:
    driver: bridge
